finalproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tasks/', include('taskmanager.urls')),
    path('books/', include('librarymanager.urls')),
    path('contacts/', include('listofcontacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='home'),
]

librarymanager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('book/new/', views.book_create, name='book_create'),
    path('book/<int:pk>/edit/', views.book_update, name='book_update'),
    path('book/<int:pk>/delete/', views.book_delete, name='book_delete'),
]

librarymanager/models.py
from django.db import models
import os

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='book_images/', blank=True, null=True)
    author = models.CharField(max_length=100)
    published_date = models.DateField()
    ISBN = models.CharField(max_length=13, unique=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        try:
            old_image = Book.objects.get(pk=self.pk).image
        except Book.DoesNotExist:
            old_image = None

        super(Book, self).save(*args, **kwargs)

        if old_image and old_image != self.image:
            if os.path.isfile(old_image.path):
                os.remove(old_image.path)
    
    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super().delete(*args, **kwargs)

librarymanager/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'image', 'author', 'published_date', 'ISBN']
        widgets = {
            'published_date': forms.DateInput(attrs={'type': 'date'}),
        }

librarymanager/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from .forms import BookForm
import os

# Create your views here.
def book_list(request):
    books = Book.objects.all()
    return render(request, 'library_manager/book_list.html', {'books': books})

def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'library_manager/book_form.html', {'form': form})

def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            if 'image' in request.FILES or 'image-clear' in request.POST:
                if book.image:
                    if os.path.isfile(book.image.path):
                        os.remove(book.image.path)
            form.save()
            return redirect('book_list')
    else:
        form = BookForm(instance=book)
    return render(request, 'library_manager/book_form.html', {'form': form})

def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('book_list')
    return render(request, 'library_manager/book_confirm_delete.html', {'book': book})

librarymanager/templates/library_manager/book_confirm_delete.html
{% extends "layout.html" %} {% block title %}Confirm Delete{% endblock %}
<!--Separator Comment-->{%block content %}
<h2 class="mb-3">Confirm Delete</h2>
<p>
  Are you sure you want to delete "{{ book.title }}" by "{{ book.author }}"?
</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Yes, delete</button>
</form>
{% endblock %}

librarymanager/templates/library_manager/book_form.html
{% extends 'layout.html' %}
{% block title %}
  Book Form
{% endblock %}

{% block content %}
  <h2 class="mb-3"><i class="fa-solid fa-pen-to-square"></i> Book Form</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_title" class="form-label">Title:</label>
      {{ form.title }}
    </div>
    <div class="mb-3">
      <label for="id_image" class="form-label">Image:</label>
      {{ form.image }}
    </div>
    <div class="mb-3">
      <label for="id_author" class="form-label">Author:</label>
      {{ form.author }}
    </div>
    <div class="mb-3">
      <label for="id_published_date" class="form-label">Published Date:</label>
      {{ form.published_date }}
    </div>
    <div class="mb-3">
      <label for="id_ISBN" class="form-label">ISBN:</label>
      {{ form.ISBN }}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}

librarymanager/templates/library_manager/book_list.html
{% extends 'layout.html' %}
{% block title %}
  Book List
{% endblock %}
{% block content %}
  <h2 class="mb-3"><i class="fas fa-book"></i> Book List</h2>
  <a class="btn btn-primary mb-3" href="{% url 'book_create' %}">Add Book</a>
  <div class="row">
    {% for book in books %}
      <div class="col-md-4 mb-3">
        <div class="card">
          <img src="{{ book.image.url }}" alt="{{ book.title }}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.author }} - {{ book.published_date }}</p>
            <a href="{% url 'book_update' book.pk %}" class="btn btn-sm btn-secondary">Edit</a>
            <a href="{% url 'book_delete' book.pk %}" class="btn btn-sm btn-danger">Delete</a>
          </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:3 %}
        </div><div class="row">
      {% endif %}
    {% endfor %}
  </div>
  <a class="btn btn-secondary mt-3" href="{% url 'home' %}">Back to Home</a>
{% endblock %}